[project]
name = "ai-tutor"
version = "0.1.0"
description = "ai tutoring system"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "bitsandbytes==0.42.0",
    "openai>=1.100.0",
    "peft>=0.17.0",
    "pillow>=11.3.0",
    "trl>=0.21.0",
]
